import SpotifyWebApi from "spotify-web-api-node";
export const token =
  "BQDGmzjebaph4XLeAmOcfXUqbkAIChX1a4WgT2qOACIO9whP3n3pSYTaLfLoe4Ts-I8YLwFPvtPOMUUvHEbmMJ4vdCnWFPcD-nU7G29pYd5h0anPiiwOa6WWCFdD_aqlb8nv4y4zdVgjxprgddqN3urfdlOuTDb-fxUfOlUW2Q5lkR42dFH1LA";
